/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: OAuth > Token
 * Request UID: 52041987-ced3cc2e-170e-40fa-8f39-fee0f6a464d7
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type { NotionError } from "../../shared/types.js";

/** Parameters for the OAuth token exchange */
export interface OAuthTokenParams {
  /** Grant type — typically "authorization_code" */
  grant_type: string;
  /** Authorization code received from the OAuth flow */
  code: string;
  /** Redirect URI used in the authorization request */
  redirect_uri: string;
}

/** Response from the OAuth token endpoint */
export interface OAuthTokenResponse {
  access_token: string;
  token_type: string;
  bot_id: string;
  workspace_name: string;
  workspace_icon: string | null;
  workspace_id: string;
  owner?: unknown;
  duplicated_template_id?: string | null;
}

/**
 * Exchange an authorization code for an access token.
 *
 * This endpoint uses Basic authentication with your OAuth client_id and client_secret.
 * Encode them as base64(client_id:client_secret) for the Authorization header.
 *
 * @param params - Token exchange parameters (grant_type, code, redirect_uri)
 * @param clientId - OAuth client ID
 * @param clientSecret - OAuth client secret
 * @returns The OAuth token response with access_token
 * @throws Error if the request fails
 */
export async function oauthToken(
  params: OAuthTokenParams,
  clientId: string,
  clientSecret: string
): Promise<OAuthTokenResponse> {
  const url = "https://api.notion.com/v1/oauth/token";
  const credentials = btoa(`${clientId}:${clientSecret}`);

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as OAuthTokenResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
