/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Request: Databases > Query a database
 * Request UID: 15568543-cddcc0aa-d534-4744-b37a-ddf36dee7d8f
 * Request modified at: 2023-09-05T16:53:05.000Z
 */

import type {
  QueryDatabaseParams,
  QueryDatabaseResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Query a database.
 *
 * Gets a list of pages contained in the database, filtered and ordered
 * according to the filter and sort criteria provided in the request body.
 *
 * @param databaseId - The ID of the database to query
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version (default: 2022-02-22)
 * @param params - Optional filter, sort, and pagination parameters
 * @returns Paginated list of pages in the database
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-database-query
 */
export async function queryDatabase(
  databaseId: string,
  bearerToken: string,
  notionVersion: string = "2022-02-22",
  params: QueryDatabaseParams = {}
): Promise<QueryDatabaseResponse> {
  const url = `https://api.notion.com/v1/databases/${encodeURIComponent(databaseId)}/query`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as QueryDatabaseResponse;
  }

  const error = (await response.json()) as NotionError;

  switch (response.status) {
    case 400:
      throw new Error(`Bad Request: ${error.message}`);
    case 401:
      throw new Error(`Unauthorized: ${error.message}`);
    case 404:
      throw new Error(`Database not found: ${error.message}`);
    case 429:
      throw new Error(`Rate limited: ${error.message}`);
    default:
      throw new Error(`Notion API error (${response.status}): ${error.message}`);
  }
}
