/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Users > Retrieve your token's bot user
 * Request UID: 52041987-30ad8b7b-5eb0-4bbe-bfbf-509d7f961cae
 * Request modified at: 2024-01-29T18:38:30.000Z
 */

import type { NotionUser, NotionError } from "../../shared/types.js";

/**
 * Retrieve the bot user associated with the current API token.
 *
 * Returns the bot user object for the integration that owns the bearer token.
 * Useful for verifying the token is valid and checking which workspace the
 * integration belongs to.
 *
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The bot user object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/get-self
 */
export async function retrieveBotUser(
  bearerToken: string,
  notionVersion: string
): Promise<NotionUser> {
  const url = "https://api.notion.com/v1/users/me";

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionUser;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
