/**
 * Generated by Postman Code
 *
 * Collection: ⭐️ Stripe API [2024-04-10]
 * Collection UID: 665823-7a054d2e-29d8-441a-8752-fb9b93d71384
 *
 * Request: Payment Intents > Create a PaymentIntent
 * Request UID: 665823-95f5a7c9-8ad6-4574-8613-05694c82b896
 * Request modified at: 2024-04-16T16:37:09.000Z
 */

import type { CreatePaymentIntentParams, PaymentIntent, StripeError } from '../../shared/types.js';

/**
 * Creates a PaymentIntent object.
 *
 * After the PaymentIntent is created, attach a payment method and confirm
 * to continue the payment. When you use `confirm=true` during creation,
 * it's equivalent to creating and confirming the PaymentIntent in the same call.
 *
 * @param apiKey - Stripe secret API key
 * @param baseUrl - Stripe API base URL
 * @param params - PaymentIntent parameters
 * @returns The created PaymentIntent
 * @throws Error if the request fails
 *
 * @example
 * const paymentIntent = await createPaymentIntent(
 *   'sk_test_...',
 *   'https://api.stripe.com',
 *   {
 *     amount: 1000,
 *     currency: 'usd',
 *     confirm: true,
 *     payment_method_data: {
 *       type: 'card',
 *       card: {
 *         number: '4242424242424242',
 *         exp_month: 12,
 *         exp_year: 2025,
 *         cvc: '123',
 *       },
 *     },
 *   }
 * );
 */
export async function createPaymentIntent(
  apiKey: string,
  baseUrl: string,
  params: CreatePaymentIntentParams
): Promise<PaymentIntent> {
  const url = `${baseUrl}/v1/payment_intents`;

  // Build form-urlencoded body
  const body = new URLSearchParams();
  body.append('amount', String(params.amount));
  body.append('currency', params.currency);

  if (params.confirm !== undefined) {
    body.append('confirm', String(params.confirm));
  }

  if (params.description) {
    body.append('description', params.description);
  }

  if (params.receipt_email) {
    body.append('receipt_email', params.receipt_email);
  }

  if (params.payment_method) {
    body.append('payment_method', params.payment_method);
  }

  if (params.return_url) {
    body.append('return_url', params.return_url);
  }

  // Handle automatic payment methods
  if (params.automatic_payment_methods) {
    body.append('automatic_payment_methods[enabled]', String(params.automatic_payment_methods.enabled));
    if (params.automatic_payment_methods.allow_redirects) {
      body.append('automatic_payment_methods[allow_redirects]', params.automatic_payment_methods.allow_redirects);
    }
  }

  // Handle inline payment method data
  if (params.payment_method_data) {
    body.append('payment_method_data[type]', params.payment_method_data.type);

    if (params.payment_method_data.type === 'card' && params.payment_method_data.card) {
      const card = params.payment_method_data.card;
      body.append('payment_method_data[card][number]', card.number);
      body.append('payment_method_data[card][exp_month]', String(card.exp_month));
      body.append('payment_method_data[card][exp_year]', String(card.exp_year));
      body.append('payment_method_data[card][cvc]', card.cvc);
    }
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: body.toString(),
  });

  const data = await response.json();

  if (!response.ok) {
    const error = data as StripeError;
    const message = error.error?.message || 'Unknown error';
    const code = error.error?.code || 'unknown';
    throw new Error(`Stripe API error (${code}): ${message}`);
  }

  return data as PaymentIntent;
}

