# Generated by Postman Code
#
# Collection: Google Maps Reviews API
# Collection UID: 45090949-3caef9d4-da80-440f-a797-797da2899bd5
#
# Request: search > Google Maps Reviews Search
# Request UID: 45090949-af449e26-7004-4cb2-9274-1c95f23e0a72
# Request modified at: 2025-09-07T03:23:37.000Z

from typing import TypedDict

import requests

from postman.google_maps_search_api.shared.errors import (
    SearchApiError,
    handle_response,
)


class PlaceResult(TypedDict, total=False):
    title: str
    address: str
    phone: str
    rating: float
    reviews: int
    reviews_histogram: dict[str, int]
    type: str


class Topic(TypedDict, total=False):
    id: str
    keyword: str
    reviews: int


class ReviewUser(TypedDict, total=False):
    name: str
    thumbnail: str
    link: str
    contributor_id: str
    is_local_guide: bool
    reviews: int
    photos: int


class ReviewImage(TypedDict, total=False):
    id: str
    image: str


class ReviewResponse(TypedDict, total=False):
    date: str
    iso_date: str
    text: str
    translated_text: str


class Review(TypedDict, total=False):
    review_id: str
    user: ReviewUser
    link: str
    source: str
    text: str
    date: str
    iso_date: str
    translated_text: str
    rating: int
    rating_details: dict
    likes: int
    images: list[ReviewImage]
    response: ReviewResponse


class Pagination(TypedDict, total=False):
    next_page_token: str


class GoogleMapsReviewsResponse(TypedDict, total=False):
    search_metadata: dict
    search_parameters: dict
    place_result: PlaceResult
    topics: list[Topic]
    reviews: list[Review]
    pagination: Pagination
    error: str


def google_maps_reviews_search(
    base_url: str,
    api_key: str,
    place_id: str | None = None,
    data_id: str | None = None,
    hl: str = "en",
    search_query: str | None = None,
    topic_id: str | None = None,
    sort_by: str = "most_relevant",
    num: int = 10,
    next_page_token: str | None = None,
) -> GoogleMapsReviewsResponse:
    """Get user reviews and ratings for a place on Google Maps.

    Provide either place_id or data_id (at least one is required). These
    identifiers come from Google Maps Search or Place Details results.

    Args:
        base_url: The API base URL (e.g. "https://www.searchapi.io/api/v1").
        api_key: SearchApi API key for authentication.
        place_id: Google Maps place ID.
        data_id: Google Maps data ID.
        hl: Language for search results (default "en").
        search_query: Filter reviews by keyword.
        topic_id: Filter reviews by topic ID (from the topics response field).
        sort_by: Sort order — "most_relevant", "newest", "highest_rating",
            or "lowest_rating" (default "most_relevant").
        num: Number of reviews per page (default 10).
        next_page_token: Pagination token from a previous response.

    Returns:
        GoogleMapsReviewsResponse with:
            - place_result: summary with title, address, rating, reviews,
              reviews_histogram.
            - topics: list of review topics with id, keyword, count.
            - reviews: list of reviews with user info, text, date, rating,
              likes, images, and owner response.
            - pagination: next_page_token for fetching more reviews.

    Raises:
        ValidationError: 400 — invalid or missing query parameters.
        AuthenticationError: 401 — API key is missing or invalid.
        RateLimitError: 429 — request limit exceeded.
        ServerError: 500 — internal server error.
        TimeoutError: 503 — results not retrieved within 90 seconds.
    """
    params: dict = {
        "engine": "google_maps_reviews",
        "api_key": api_key,
        "hl": hl,
        "sort_by": sort_by,
        "num": num,
    }
    if place_id is not None:
        params["place_id"] = place_id
    if data_id is not None:
        params["data_id"] = data_id
    if search_query is not None:
        params["search_query"] = search_query
    if topic_id is not None:
        params["topic_id"] = topic_id
    if next_page_token is not None:
        params["next_page_token"] = next_page_token

    response = requests.get(
        f"{base_url}/search",
        params=params,
        headers={"Accept": "application/json"},
    )
    return handle_response(response)
