/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: OAuth > Introspect
 * Request UID: 52041987-3070c020-0b6d-402f-bd18-88e9e1348521
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type { NotionError } from "../../shared/types.js";

/** Response from the OAuth introspect endpoint */
export interface OAuthIntrospectResponse {
  active: boolean;
  bot_id?: string;
  workspace_id?: string;
  token_type?: string;
  /** When the token was issued (ISO 8601) */
  iat?: string;
  /** When the token expires (ISO 8601) */
  exp?: string;
  [key: string]: unknown;
}

/**
 * Introspect a token to get its metadata.
 *
 * This endpoint uses Basic authentication with your OAuth client_id and client_secret.
 *
 * @param token - The token to introspect
 * @param clientId - OAuth client ID
 * @param clientSecret - OAuth client secret
 * @returns Token metadata including active status
 * @throws Error if the request fails
 */
export async function oauthIntrospect(
  token: string,
  clientId: string,
  clientSecret: string
): Promise<OAuthIntrospectResponse> {
  const url = "https://api.notion.com/v1/oauth/introspect";
  const credentials = btoa(`${clientId}:${clientSecret}`);

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ token }),
  });

  if (response.ok) {
    return (await response.json()) as OAuthIntrospectResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
