/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Databases > Retrieve a database
 * Request UID: 52041987-73359528-2278-415f-98f2-4d20274cc69e
 * Request modified at: 2022-03-02T05:38:32.000Z
 */

import type { NotionDatabase, NotionError } from "../../shared/types.js";

/**
 * Retrieve a database by ID.
 *
 * Retrieves a Database object using the ID specified in the request path.
 * This endpoint exposes the database schema (properties), not the database rows.
 *
 * @param databaseId - The ID of the database to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The database object with schema
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-database
 */
export async function retrieveDatabase(
  databaseId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const url = `https://api.notion.com/v1/databases/${encodeURIComponent(databaseId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
