/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Blocks > Append block children
 * Request UID: 52041987-a9376866-eb97-4cfa-b08d-5fc49f09ef26
 * Request modified at: 2023-09-04T19:06:11.000Z
 */

import type { AppendBlockChildrenResponse, NotionError } from "../../shared/types.js";

/**
 * Append child blocks to a parent block or page.
 *
 * Creates and appends new children blocks to the parent block_id specified.
 * Returns the newly created first-level children blocks.
 *
 * @param blockId - The ID of the parent block or page
 * @param children - Array of block objects to append
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns A list response containing the appended blocks
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/patch-block-children
 */
export async function appendBlockChildren(
  blockId: string,
  children: unknown[],
  bearerToken: string,
  notionVersion: string
): Promise<AppendBlockChildrenResponse> {
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}/children`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify({ children }),
  });

  if (response.ok) {
    return (await response.json()) as AppendBlockChildrenResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
