/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Users > Retrieve a user
 * Request UID: 52041987-e23bf76f-cb3a-4bbc-9e5a-0a39cd59e909
 * Request modified at: 2026-02-02T22:04:41.000Z
 */

import type { NotionUser, NotionError } from "../../shared/types.js";

/**
 * Retrieve a user object using the ID specified.
 *
 * Returns a full user object for any user (person or bot) in the workspace.
 *
 * @param userId - The ID of the user to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The user object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/get-user
 */
export async function retrieveUser(
  userId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionUser> {
  const url = `https://api.notion.com/v1/users/${encodeURIComponent(userId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionUser;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
