/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Search > Search
 * Request UID: 52041987-0e8a4f2d-d453-4bc1-b4c6-286905b87f4a
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type {
  SearchParams,
  SearchResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Search all pages and databases the integration has access to.
 *
 * Searches all original pages, databases, and child pages/databases that are
 * shared with the integration. It will not return linked databases.
 *
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional search parameters including query, filter, and pagination
 * @returns The search results containing pages and databases
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-search
 */
export async function search(
  bearerToken: string,
  notionVersion: string,
  params: SearchParams = {}
): Promise<SearchResponse> {
  const url = "https://api.notion.com/v1/search";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as SearchResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
