/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Request: Search > Search
 * Request UID: 15568543-816435ec-1d78-4c55-a85e-a1a4a8a24564
 * Request modified at: 2022-02-24T23:01:58.000Z
 */

import type {
  SearchParams,
  SearchResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Search all pages and databases the integration has access to.
 *
 * Searches all original pages, databases, and child pages/databases that are
 * shared with the integration. It will not return linked databases.
 *
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version (default: 2022-02-22)
 * @param params - Optional search parameters including query, filter, and pagination
 * @returns The search results containing pages and databases
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-search
 */
export async function search(
  bearerToken: string,
  notionVersion: string = "2022-02-22",
  params: SearchParams = {}
): Promise<SearchResponse> {
  const url = "https://api.notion.com/v1/search";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as SearchResponse;
  }

  const error = (await response.json()) as NotionError;

  switch (response.status) {
    case 400:
      throw new Error(`Bad Request: ${error.message}`);
    case 401:
      throw new Error(`Unauthorized: ${error.message}`);
    case 429:
      throw new Error(`Rate limited: ${error.message}`);
    default:
      throw new Error(`Notion API error (${response.status}): ${error.message}`);
  }
}
