/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Request: Databases > Retrieve a database
 * Request UID: 15568543-095c448d-2373-4aee-9b9e-ed3cf58afbe3
 * Request modified at: 2022-03-02T05:38:32.000Z
 */

import type { NotionDatabase, NotionError } from "../../shared/types.js";

/**
 * Retrieve a database by ID.
 *
 * Retrieves a Database object using the ID specified in the request path.
 * This endpoint exposes the database schema (properties), not the database rows.
 *
 * @param databaseId - The ID of the database to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version (default: 2022-02-22)
 * @returns The database object with schema
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-database
 */
export async function retrieveDatabase(
  databaseId: string,
  bearerToken: string,
  notionVersion: string = "2022-02-22"
): Promise<NotionDatabase> {
  const url = `https://api.notion.com/v1/databases/${encodeURIComponent(databaseId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;

  switch (response.status) {
    case 400:
      throw new Error(`Bad Request: ${error.message}`);
    case 401:
      throw new Error(`Unauthorized: ${error.message}`);
    case 404:
      throw new Error(`Database not found: ${error.message}`);
    case 429:
      throw new Error(`Rate limited: ${error.message}`);
    default:
      throw new Error(`Notion API error (${response.status}): ${error.message}`);
  }
}
