/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Update page properties
 * Request UID: 52041987-de2726f0-1465-4fdc-81d5-bd35415848b4
 * Request modified at: 2023-09-04T19:08:43.000Z
 */

import type { UpdatePageParams, NotionPage, NotionError } from "../../shared/types.js";

/**
 * Update a page's properties.
 *
 * Can update property values, icon, cover, and archived status.
 * Only the properties included in the request body are updated;
 * omitted properties remain unchanged.
 *
 * @param pageId - The ID of the page to update
 * @param params - Properties and/or metadata to update
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The updated page object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/patch-page
 */
export async function updatePageProperties(
  pageId: string,
  params: UpdatePageParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionPage> {
  const url = `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
