/**
 * Generated by Postman Code
 *
 * Collection: ⭐️ Stripe API [2024-04-10]
 * Collection UID: 665823-7a054d2e-29d8-441a-8752-fb9b93d71384
 *
 * Request: Payment Intents > Retrieve a PaymentIntent
 * Request UID: 665823-2444961c-e8c3-4b99-8e85-936a55274455
 * Request modified at: 2024-04-16T16:37:09.000Z
 */

import type { PaymentIntent, StripeError } from '../../shared/types.js';

/**
 * Retrieves the details of a PaymentIntent that has previously been created.
 *
 * @param apiKey - Stripe secret API key
 * @param baseUrl - Stripe API base URL
 * @param intentId - The PaymentIntent ID (starts with pi_)
 * @returns The retrieved PaymentIntent
 * @throws Error if the request fails
 *
 * @example
 * const paymentIntent = await retrievePaymentIntent(
 *   'sk_test_...',
 *   'https://api.stripe.com',
 *   'pi_1234567890'
 * );
 * console.log(paymentIntent.status); // 'succeeded'
 */
export async function retrievePaymentIntent(
  apiKey: string,
  baseUrl: string,
  intentId: string
): Promise<PaymentIntent> {
  const url = `${baseUrl}/v1/payment_intents/${intentId}`;

  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  });

  const data = await response.json();

  if (!response.ok) {
    const error = data as StripeError;
    const message = error.error?.message || 'Unknown error';
    const code = error.error?.code || 'unknown';

    // Handle specific error cases
    if (response.status === 404) {
      throw new Error(`PaymentIntent not found: ${intentId}`);
    }

    throw new Error(`Stripe API error (${code}): ${message}`);
  }

  return data as PaymentIntent;
}

