/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Comments > Create a comment
 * Request UID: 52041987-9261f5ec-6b04-4d13-83a0-d12fe1b188c7
 * Request modified at: 2022-07-20T17:24:32.000Z
 */

import type { NotionComment, NotionError } from "../../shared/types.js";

type RichTextItem = { text: { content: string; link?: { url: string } | null } };

/**
 * Parameters for creating a comment.
 *
 * Provide **one** of:
 * - `parent.page_id` — creates a new top-level comment thread on a page
 * - `discussion_id` — replies to an existing comment thread
 */
export interface CreateCommentParams {
  /** Start a new comment thread on this page. */
  parent?: { page_id: string };
  /** Reply to an existing discussion thread. */
  discussion_id?: string;
  /** The comment body as rich text. */
  rich_text: RichTextItem[];
}

/**
 * Create a comment — either a new page thread or a reply to an existing discussion.
 *
 * The Notion API uses the same `POST /v1/comments` endpoint for both cases;
 * the request body determines the behavior.
 *
 * @param params - Comment creation parameters (page comment or discussion reply)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The created comment object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/create-a-comment
 */
export async function createComment(
  params: CreateCommentParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionComment> {
  const response = await fetch("https://api.notion.com/v1/comments", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionComment;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
