# Generated by Postman Code
#
# Collection: Google Maps Search API
# Collection UID: 45090949-36a5cde4-8b66-450f-b3d5-d28cfb535b56
#
# Request: search > Google Maps Search
# Request UID: 45090949-1550053b-aabf-40a4-a28a-59e40e43b7b7
# Request modified at: 2026-02-12T23:35:52.000Z

from typing import TypedDict

import requests

from postman.google_maps_search_api.shared.errors import (
    SearchApiError,
    handle_response,
)


class GpsCoordinates(TypedDict, total=False):
    latitude: float
    longitude: float


class Post(TypedDict, total=False):
    title: str
    source: str
    link: str


class ReservationLink(TypedDict, total=False):
    text: str
    link: str


class ExtensionItem(TypedDict, total=False):
    title: str
    value: str


class Extension(TypedDict, total=False):
    title: str
    items: list[ExtensionItem]


class LocalResult(TypedDict, total=False):
    position: int
    ludocid: str
    place_id: str
    kgmid: str
    data_id: str
    title: str
    description: str
    features: list[str]
    address: str
    phone: str
    price: str
    price_description: str
    hotel_stars: int
    rating: float
    reviews: int
    reviews_link: str
    review_text: str
    is_unclaimed_listing: bool
    website: str
    domain: str
    gps_coordinates: GpsCoordinates
    type: str
    types: list[str]
    tracking_title: str
    tracking_link: str
    posts: list[Post]
    amenities: list[str]
    open_state: str
    hours: str
    open_hours: dict[str, str]
    reservation_links: list[ReservationLink]
    extensions: list[Extension]
    images: list[str]
    thumbnail: str


class SearchInformation(TypedDict, total=False):
    query_displayed: str
    did_you_mean: str
    state: str


class SearchMetadata(TypedDict, total=False):
    id: str
    status: str
    created_at: str
    request_time_taken: float
    parsing_time_taken: float
    total_time_taken: float
    request_url: str
    html_url: str
    json_url: str


class GoogleMapsSearchResponse(TypedDict, total=False):
    search_metadata: SearchMetadata
    search_parameters: dict
    search_information: SearchInformation
    ads: list[LocalResult]
    local_results: list[LocalResult]


def google_maps_search(
    base_url: str,
    api_key: str,
    q: str,
    ll: str | None = None,
    hl: str = "en",
    gl: str | None = None,
    page: int = 1,
) -> GoogleMapsSearchResponse:
    """Search Google Maps for local businesses, places, and locations.

    Returns detailed information including ratings, reviews, contact details,
    and GPS coordinates. The place_id from results can be used with the
    Google Maps Place, Reviews, and Photos APIs.

    Args:
        base_url: The API base URL (e.g. "https://www.searchapi.io/api/v1").
        api_key: SearchApi API key for authentication.
        q: Search query — anything you'd type into Google Maps.
        ll: GPS coordinates with zoom/radius, e.g. "@40.7009973,-73.994778,12z"
            or "@40.7009973,-73.994778,500m". Optional but improves accuracy.
        hl: Interface language (default "en").
        gl: Country code for the search (ISO 3166-1 alpha-2).
        page: Page number for pagination (default 1).

    Returns:
        GoogleMapsSearchResponse with:
            - local_results: list of places with place_id, title, address,
              phone, rating, reviews, gps_coordinates, type, website.
            - ads: sponsored listings with the same structure.
            - search_information: query metadata.

    Raises:
        ValidationError: 400 — invalid or missing query parameters.
        AuthenticationError: 401 — API key is missing or invalid.
        RateLimitError: 429 — request limit exceeded.
        ServerError: 500 — internal server error.
        TimeoutError: 503 — results not retrieved within 90 seconds.
    """
    params: dict = {
        "engine": "google_maps",
        "api_key": api_key,
        "q": q,
        "hl": hl,
        "page": page,
    }
    if ll is not None:
        params["ll"] = ll
    if gl is not None:
        params["gl"] = gl

    response = requests.get(
        f"{base_url}/search",
        params=params,
        headers={"Accept": "application/json"},
    )
    return handle_response(response)
