/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: File uploads > Retrieve a file upload
 * Request UID: 52041987-2f30fd9c-c12b-40fc-bb98-03d153c3e353
 * Request modified at: 2026-02-02T22:37:45.000Z
 */

import type { NotionError } from "../../shared/types.js";
import type { FileUpload } from "../create-file-upload/client.js";

/**
 * Retrieve a file upload by ID.
 *
 * @param fileUploadId - The ID of the file upload to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The file upload object
 * @throws Error if the request fails
 */
export async function retrieveFileUpload(
  fileUploadId: string,
  bearerToken: string,
  notionVersion: string
): Promise<FileUpload> {
  const url = `https://api.notion.com/v1/file_uploads/${encodeURIComponent(fileUploadId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as FileUpload;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
