/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Data sources > List data source templates
 * Request UID: 52041987-f38c907f-36d5-40c7-b057-e4811b4b5cde
 * Request modified at: 2026-02-02T22:36:03.000Z
 */

import type { NotionError } from "../../shared/types.js";

/** A data source template */
export interface DataSourceTemplate {
  id: string;
  name: string;
  is_default: boolean;
}

/** Response from list data source templates endpoint */
export interface ListDataSourceTemplatesResponse {
  templates: DataSourceTemplate[];
  has_more: boolean;
  next_cursor: string | null;
}

/** Parameters for listing data source templates */
export interface ListDataSourceTemplatesParams {
  /** Filter templates by name (case-insensitive substring match) */
  name?: string;
  /** Pagination cursor */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/**
 * List available templates for a data source.
 *
 * @param dataSourceId - The ID of the data source
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional filter and pagination parameters
 * @returns List of available templates
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/list-data-source-templates
 */
export async function listDataSourceTemplates(
  dataSourceId: string,
  bearerToken: string,
  notionVersion: string,
  params: ListDataSourceTemplatesParams = {}
): Promise<ListDataSourceTemplatesResponse> {
  const queryParams = new URLSearchParams();
  if (params.name) queryParams.set("name", params.name);
  if (params.start_cursor) queryParams.set("start_cursor", params.start_cursor);
  if (params.page_size) queryParams.set("page_size", String(params.page_size));

  const qs = queryParams.toString();
  const url = `https://api.notion.com/v1/data_sources/${encodeURIComponent(dataSourceId)}/templates${qs ? `?${qs}` : ""}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as ListDataSourceTemplatesResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
