/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Databases > Create a database
 * Request UID: 52041987-85ab373b-2fc1-4b9a-a8a6-ee6b9e72728c
 * Request modified at: 2022-03-02T05:38:33.000Z
 */

import type { CreateDatabaseParams, NotionDatabase, NotionError } from "../../shared/types.js";

/**
 * Create a database as a child of a page.
 *
 * The database schema is defined by the properties object.
 * At minimum, a title property is required.
 *
 * @param params - Database creation parameters (parent, title, properties)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The created database object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/create-a-database
 */
export async function createDatabase(
  params: CreateDatabaseParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const response = await fetch("https://api.notion.com/v1/databases", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
