/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Complete file upload
 * Request UID: 52041987-80549896-30b1-43a4-add0-a73958b602e1
 * Request modified at: 2026-02-02T22:37:45.000Z
 */

import type { NotionError } from "../../shared/types.js";
import type { FileUpload } from "../create-file-upload/client.js";

/**
 * Complete a file upload after all chunks have been sent.
 *
 * @param fileUploadId - The ID of the file upload to complete
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The completed file upload object
 * @throws Error if the request fails
 */
export async function completeFileUpload(
  fileUploadId: string,
  bearerToken: string,
  notionVersion: string
): Promise<FileUpload> {
  const url = `https://api.notion.com/v1/file_uploads/${encodeURIComponent(fileUploadId)}/complete`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as FileUpload;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
