# Generated by Postman Code
#
# Collection: Google Maps Directions API
# Collection UID: 45090949-c8e76bd2-c6bf-4a5a-92a5-44da51c77e93
#
# Request: search > Google Maps Directions Search
# Request UID: 45090949-6998d678-940a-4133-ba91-f21b02d71c90
# Request modified at: 2026-02-12T23:35:52.000Z

from typing import TypedDict

import requests

from postman.google_maps_search_api.shared.errors import (
    SearchApiError,
    handle_response,
)


class Coordinates(TypedDict, total=False):
    latitude: float
    longitude: float


class PlaceInfo(TypedDict, total=False):
    address: str
    data_id: str
    coordinates: Coordinates


class TravelMode(TypedDict, total=False):
    travel_mode: str
    formatted_duration: str
    duration: int


class TimeWindow(TypedDict, total=False):
    depart_at: str
    depart_at_tz: str
    arrive_at: str
    arrive_at_tz: str


class TicketOffer(TypedDict, total=False):
    source: str
    price: str
    easy_checkout: bool
    link: str
    favicon: str


class BuyTicket(TypedDict, total=False):
    title: str
    price: str
    offers: list[TicketOffer]


class TransitStop(TypedDict, total=False):
    place: str
    at: str
    platform: str
    timezone: str
    latitude: float
    longitude: float
    data_id: str


class ServiceProvider(TypedDict, total=False):
    name: str
    contact: str
    website: str


class Instruction(TypedDict, total=False):
    travel_mode: str
    action: str
    information: str
    formatted_duration: str
    formatted_distance: str
    duration: int
    distance: int
    latitude: float
    longitude: float
    street_view: str
    depart_from: TransitStop
    direction: str
    vehicle: str
    line_name: str
    line_number: str
    arrive_at: TransitStop
    service_provider: ServiceProvider
    stops: list[TransitStop]


class Direction(TypedDict, total=False):
    travel_mode: str
    distance: int
    duration: int
    formatted_distance: str
    formatted_duration: str
    via: str
    formatted_typical_duration: str
    optimistic_duration: int
    pessimistic_duration: int
    warnings: list[str]
    frequency: str
    time_window: TimeWindow
    buy_ticket: BuyTicket
    departure: str
    arrival: str
    formatted_price: str
    price: int
    airlines: str
    flights_link: str
    instructions: list[Instruction]


class GoogleMapsDirectionsResponse(TypedDict, total=False):
    search_metadata: dict
    search_parameters: dict
    error: str
    travel_modes: list[TravelMode]
    places_info: list[PlaceInfo]
    directions: list[Direction]


def google_maps_directions_search(
    base_url: str,
    api_key: str,
    from_location: str,
    to_location: str,
    waypoints: str | None = None,
    travel_mode: str = "best",
    time: str | None = None,
    route: str = "best",
    prefer: str | None = None,
    avoid: str | None = None,
    distance_units: str = "automatic",
    gl: str = "us",
    hl: str = "en",
) -> GoogleMapsDirectionsResponse:
    """Get directions between two locations via Google Maps.

    Returns suggested routes with distances, estimated travel times, and
    turn-by-turn instructions.

    Args:
        base_url: The API base URL (e.g. "https://www.searchapi.io/api/v1").
        api_key: SearchApi API key for authentication.
        from_location: Starting point — address, data ID, or "lat,long".
        to_location: Destination — address, data ID, or "lat,long".
        waypoints: JSON array of intermediate stops (max 8). Not supported
            with transit mode or the time parameter.
        travel_mode: Transportation mode — "best", "driving", "transit",
            "walking", "cycling", or "flying" (default "best").
        time: Time-aware routing. Format: "depart_at:<timestamp>",
            "arrive_by:<timestamp>", or "last_available" (transit only).
        route: Routing preference for transit — "best", "fewer_transfers",
            or "less_walking" (default "best").
        prefer: JSON array of transit preferences, e.g. '["bus", "subway"]'.
            Transit mode only.
        avoid: JSON array of features to avoid, e.g. '["tolls", "highways"]'.
        distance_units: "automatic", "km", or "miles" (default "automatic").
        gl: Country code (default "us").
        hl: Language (default "en").

    Returns:
        GoogleMapsDirectionsResponse with:
            - travel_modes: available modes with formatted_duration.
            - places_info: origin/destination with address, data_id, coordinates.
            - directions: list of routes with distance, duration,
              formatted_distance, formatted_duration, via, and
              instructions (turn-by-turn steps with action, distance,
              duration, street_view, transit stops).

    Raises:
        ValidationError: 400 — invalid or missing query parameters.
        AuthenticationError: 401 — API key is missing or invalid.
        RateLimitError: 429 — request limit exceeded.
        ServerError: 500 — internal server error.
        TimeoutError: 503 — results not retrieved within 90 seconds.
    """
    params: dict = {
        "engine": "google_maps_directions",
        "api_key": api_key,
        "from": from_location,
        "to": to_location,
        "travel_mode": travel_mode,
        "route": route,
        "distance_units": distance_units,
        "gl": gl,
        "hl": hl,
    }
    if waypoints is not None:
        params["waypoints"] = waypoints
    if time is not None:
        params["time"] = time
    if prefer is not None:
        params["prefer"] = prefer
    if avoid is not None:
        params["avoid"] = avoid

    response = requests.get(
        f"{base_url}/search",
        params=params,
        headers={"Accept": "application/json"},
    )
    return handle_response(response)
