/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Blocks > Retrieve block children
 * Request UID: 52041987-039ea5be-709a-4539-b021-170a63eba771
 * Request modified at: 2022-02-24T23:01:58.000Z
 */

import type {
  RetrieveBlockChildrenParams,
  RetrieveBlockChildrenResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Retrieve the children blocks of a block or page.
 *
 * Returns a paginated list of child blocks for the specified block_id.
 * Pages are also blocks, so you can use a page_id here.
 *
 * @param blockId - The ID of the block or page to get children for
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional pagination parameters
 * @returns The list of child blocks
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/get-block-children
 */
export async function retrieveBlockChildren(
  blockId: string,
  bearerToken: string,
  notionVersion: string,
  params: RetrieveBlockChildrenParams = {}
): Promise<RetrieveBlockChildrenResponse> {
  const queryParams = new URLSearchParams();
  if (params.page_size) {
    queryParams.set("page_size", params.page_size.toString());
  }
  if (params.start_cursor) {
    queryParams.set("start_cursor", params.start_cursor);
  }

  const queryString = queryParams.toString();
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}/children${queryString ? `?${queryString}` : ""}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as RetrieveBlockChildrenResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
