/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Request: Blocks > Retrieve block children
 * Request UID: 15568543-228caaa0-074b-4487-a515-efcea60e5906
 * Request modified at: 2022-02-24T23:01:58.000Z
 */

import type {
  RetrieveBlockChildrenParams,
  RetrieveBlockChildrenResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Retrieve the children blocks of a block or page.
 *
 * Returns a paginated list of child blocks for the specified block_id.
 * Pages are also blocks, so you can use a page_id here.
 *
 * @param blockId - The ID of the block or page to get children for
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version (default: 2022-02-22)
 * @param params - Optional pagination parameters
 * @returns The list of child blocks
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/get-block-children
 */
export async function retrieveBlockChildren(
  blockId: string,
  bearerToken: string,
  notionVersion: string = "2022-02-22",
  params: RetrieveBlockChildrenParams = {}
): Promise<RetrieveBlockChildrenResponse> {
  const queryParams = new URLSearchParams();
  if (params.page_size) {
    queryParams.set("page_size", params.page_size.toString());
  }
  if (params.start_cursor) {
    queryParams.set("start_cursor", params.start_cursor);
  }

  const queryString = queryParams.toString();
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}/children${queryString ? `?${queryString}` : ""}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as RetrieveBlockChildrenResponse;
  }

  const error = (await response.json()) as NotionError;

  switch (response.status) {
    case 400:
      throw new Error(`Bad Request: ${error.message}`);
    case 401:
      throw new Error(`Unauthorized: ${error.message}`);
    case 404:
      throw new Error(`Block not found: ${error.message}`);
    case 429:
      throw new Error(`Rate limited: ${error.message}`);
    default:
      throw new Error(`Notion API error (${response.status}): ${error.message}`);
  }
}
