/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: File uploads > Send file upload
 * Request UID: 52041987-aaf29c9a-7236-432d-97e8-beebee88b3cd
 * Request modified at: 2026-02-02T22:37:45.000Z
 */

import type { NotionError } from "../../shared/types.js";
import type { FileUpload } from "../create-file-upload/client.js";

/**
 * Send file data for an initialized file upload.
 *
 * Uses multipart/form-data to transmit the raw file binary under the "file" key.
 * Do NOT set Content-Type manually — fetch sets it automatically with the
 * correct multipart boundary when given a FormData body.
 *
 * @param fileUploadId - The ID of the file upload
 * @param file - File data as a Blob (or Buffer wrapped in a Blob)
 * @param filename - The file name to include in the form data
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param partNumber - Optional part number for multi-part uploads
 * @returns The updated file upload object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/send-a-file-upload
 */
export async function sendFileUpload(
  fileUploadId: string,
  file: Blob,
  filename: string,
  bearerToken: string,
  notionVersion: string,
  partNumber?: number
): Promise<FileUpload> {
  const url = `https://api.notion.com/v1/file_uploads/${encodeURIComponent(fileUploadId)}/send`;

  const formData = new FormData();
  formData.append("file", file, filename);
  if (partNumber !== undefined) {
    formData.append("part_number", String(partNumber));
  }

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      // Do NOT set Content-Type — fetch sets multipart/form-data with boundary automatically
      "Notion-Version": notionVersion,
    },
    body: formData,
  });

  if (response.ok) {
    return (await response.json()) as FileUpload;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
