/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Shared type definitions for Notion API clients.
 */

/** User reference object */
export interface UserReference {
  object: "user";
  id: string;
}

/** Parent reference for a page */
export interface PageParent {
  type: "database_id" | "page_id" | "workspace";
  database_id?: string;
  page_id?: string;
}

/** Rich text annotation */
export interface RichTextAnnotations {
  bold: boolean;
  italic: boolean;
  strikethrough: boolean;
  underline: boolean;
  code: boolean;
  color: string;
}

/** Rich text item */
export interface RichTextItem {
  type: "text";
  text: {
    content: string;
    link: { url: string } | null;
  };
  annotations: RichTextAnnotations;
  plain_text: string;
  href: string | null;
}

/** Page property value - we check type at runtime */
export interface PropertyValue {
  id: string;
  type: string;
  title?: RichTextItem[];
  [key: string]: unknown;
}

/** A Notion page object */
export interface NotionPage {
  object: "page";
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  cover: unknown | null;
  icon: unknown | null;
  parent: PageParent;
  archived: boolean;
  properties: Record<string, PropertyValue>;
  url: string;
}

/** Error response from Notion API */
export interface NotionError {
  object: "error";
  status: number;
  code: string;
  message: string;
}

// ============================================================================
// Search API types
// ============================================================================

/** Filter for search to limit results to pages or databases */
export interface SearchFilter {
  value: "page" | "database";
  property: "object";
}

/** Sort options for search */
export interface SearchSort {
  direction: "ascending" | "descending";
  timestamp: "last_edited_time";
}

/** Parameters for the search endpoint */
export interface SearchParams {
  /** Text to search for in page/database titles */
  query?: string;
  /** Filter to limit results to pages or databases */
  filter?: SearchFilter;
  /** Sort order for results */
  sort?: SearchSort;
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from search endpoint */
export interface SearchResponse {
  object: "list";
  results: NotionPage[];
  next_cursor: string | null;
  has_more: boolean;
}

// ============================================================================
// Blocks API types
// ============================================================================

/** A Notion block object */
export interface NotionBlock {
  object: "block";
  id: string;
  parent: {
    type: "page_id" | "block_id" | "database_id" | "workspace";
    page_id?: string;
    block_id?: string;
    database_id?: string;
  };
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  has_children: boolean;
  archived: boolean;
  type: string;
  // Block content varies by type - using index signature
  [key: string]: unknown;
}

/** Parameters for retrieving block children */
export interface RetrieveBlockChildrenParams {
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from retrieve block children endpoint */
export interface RetrieveBlockChildrenResponse {
  object: "list";
  results: NotionBlock[];
  next_cursor: string | null;
  has_more: boolean;
  type: "block";
  block: Record<string, never>;
}

// ============================================================================
// Databases API types
// ============================================================================

/** Database property schema (defines what properties the database has) */
export interface DatabasePropertySchema {
  id: string;
  name: string;
  type: string;
  [key: string]: unknown;
}

/** Parent reference for a database */
export interface DatabaseParent {
  type: "page_id" | "block_id" | "workspace";
  page_id?: string;
  block_id?: string;
}

/** A Notion database object */
export interface NotionDatabase {
  object: "database";
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  cover: unknown | null;
  icon: unknown | null;
  title: RichTextItem[];
  properties: Record<string, DatabasePropertySchema>;
  parent: DatabaseParent;
  url: string;
  archived: boolean;
}

/** Parameters for querying a database */
export interface QueryDatabaseParams {
  /** Filter to apply to the query */
  filter?: unknown;
  /** Sorts to apply to the query */
  sorts?: unknown[];
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from query database endpoint */
export interface QueryDatabaseResponse {
  object: "list";
  results: NotionPage[];
  next_cursor: string | null;
  has_more: boolean;
}
