/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Shared type definitions for Notion API clients.
 */

/** User reference object (lightweight, embedded in other objects) */
export interface UserReference {
  object: "user";
  id: string;
}

/** Full Notion user object */
export interface NotionUser {
  object: "user";
  id: string;
  name: string | null;
  avatar_url: string | null;
  type: "person" | "bot";
  person?: {
    email?: string;
  };
  bot?: {
    owner: {
      type: "workspace" | "user";
      workspace?: boolean;
      user?: UserReference & {
        name?: string;
        type?: string;
        person?: { email?: string };
      };
    };
    workspace_name?: string;
    workspace_id?: string;
  };
}

/** Parent reference for a page */
export interface PageParent {
  type: "database_id" | "page_id" | "workspace" | "data_source_id";
  database_id?: string;
  page_id?: string;
  data_source_id?: string;
}

/** Rich text annotation */
export interface RichTextAnnotations {
  bold: boolean;
  italic: boolean;
  strikethrough: boolean;
  underline: boolean;
  code: boolean;
  color: string;
}

/** Rich text item */
export interface RichTextItem {
  type: "text";
  text: {
    content: string;
    link: { url: string } | null;
  };
  annotations: RichTextAnnotations;
  plain_text: string;
  href: string | null;
}

/** Page property value - we check type at runtime */
export interface PropertyValue {
  id: string;
  type: string;
  title?: RichTextItem[];
  [key: string]: unknown;
}

/** A Notion page object */
export interface NotionPage {
  object: "page";
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  cover: unknown | null;
  icon: unknown | null;
  parent: PageParent;
  archived: boolean;
  in_trash?: boolean;
  properties: Record<string, PropertyValue>;
  url: string;
}

/** Error response from Notion API */
export interface NotionError {
  object: "error";
  status: number;
  code: string;
  message: string;
}

// ============================================================================
// Users API types
// ============================================================================

/** Parameters for listing users */
export interface ListUsersParams {
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from list users endpoint */
export interface ListUsersResponse {
  object: "list";
  results: NotionUser[];
  next_cursor: string | null;
  has_more: boolean;
}

// ============================================================================
// Search API types
// ============================================================================

/** Filter for search to limit results to pages or data sources (databases) */
export interface SearchFilter {
  value: "page" | "data_source";
  property: "object";
}

/** Sort options for search. Currently only "last_edited_time" is documented,
 *  but the timestamp field accepts any string to forward-support new values. */
export interface SearchSort {
  direction: "ascending" | "descending";
  timestamp: "last_edited_time" | (string & {});
}

/** Parameters for the search endpoint */
export interface SearchParams {
  /** Text to search for in page/database titles */
  query?: string;
  /** Filter to limit results to pages or databases */
  filter?: SearchFilter;
  /** Sort order for results */
  sort?: SearchSort;
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from search endpoint */
export interface SearchResponse {
  object: "list";
  results: Array<NotionPage | NotionDatabase>;
  next_cursor: string | null;
  has_more: boolean;
}

// ============================================================================
// Comments API types
// ============================================================================

/** A Notion comment object */
export interface NotionComment {
  object: "comment";
  id: string;
  parent: {
    type: "page_id" | "block_id";
    page_id?: string;
    block_id?: string;
  };
  discussion_id: string;
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  rich_text: RichTextItem[];
}

/** Parameters for retrieving comments */
export interface RetrieveCommentsParams {
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from retrieve comments endpoint */
export interface RetrieveCommentsResponse {
  object: "list";
  results: NotionComment[];
  next_cursor: string | null;
  has_more: boolean;
  type: "comment";
  comment: Record<string, never>;
}

// ============================================================================
// Pages API types
// ============================================================================

/** Parameters for creating a page */
export interface CreatePageParams {
  /** Parent page or database */
  parent: { page_id: string } | { database_id: string };
  /** Page properties (must match database schema if parent is a database) */
  properties: Record<string, unknown>;
  /** Optional child blocks to add as page content */
  children?: unknown[];
}

/** Parameters for updating page properties */
export interface UpdatePageParams {
  /** Properties to update (only included properties are changed) */
  properties?: Record<string, unknown>;
  /** Set archived status */
  archived?: boolean;
  /** Page icon */
  icon?: unknown;
  /** Page cover */
  cover?: unknown;
}

/**
 * Response from the retrieve page property endpoint.
 *
 * For simple properties (select, number, checkbox, etc.) the response is a
 * single property_item object. For paginated properties (title, rich_text,
 * relation, rollup) the response is a paginated list.
 */
export interface PagePropertyItemResponse {
  object: "property_item" | "list";
  type: string;
  /** Present when object is "list" */
  results?: Array<{ object: "property_item"; type: string; [key: string]: unknown }>;
  next_cursor?: string | null;
  has_more?: boolean;
  /** Property value — varies by type */
  [key: string]: unknown;
}

// ============================================================================
// Blocks API types
// ============================================================================

/** A Notion block object */
export interface NotionBlock {
  object: "block";
  id: string;
  parent: {
    type: "page_id" | "block_id" | "database_id" | "workspace";
    page_id?: string;
    block_id?: string;
    database_id?: string;
  };
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  has_children: boolean;
  archived: boolean;
  type: string;
  // Block content varies by type - using index signature
  [key: string]: unknown;
}

/** Response from append block children endpoint */
export interface AppendBlockChildrenResponse {
  object: "list";
  results: NotionBlock[];
  next_cursor: string | null;
  has_more: boolean;
  type: "block";
  block: Record<string, never>;
}

/** Parameters for retrieving block children */
export interface RetrieveBlockChildrenParams {
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from retrieve block children endpoint */
export interface RetrieveBlockChildrenResponse {
  object: "list";
  results: NotionBlock[];
  next_cursor: string | null;
  has_more: boolean;
  type: "block";
  block: Record<string, never>;
}

// ============================================================================
// Databases API types
// ============================================================================

/** Database property schema (defines what properties the database has) */
export interface DatabasePropertySchema {
  id: string;
  name: string;
  type: string;
  [key: string]: unknown;
}

/** Parent reference for a database */
export interface DatabaseParent {
  type: "page_id" | "block_id" | "workspace";
  page_id?: string;
  block_id?: string;
}

/** Data source reference (embedded in database responses) */
export interface DataSourceReference {
  id: string;
  name: string;
}

/** A Notion database object */
export interface NotionDatabase {
  object: "database";
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: UserReference;
  last_edited_by: UserReference;
  cover: unknown | null;
  icon: unknown | null;
  title: RichTextItem[];
  properties: Record<string, DatabasePropertySchema>;
  parent: DatabaseParent;
  url: string;
  archived: boolean;
  is_locked?: boolean;
  in_trash?: boolean;
  data_sources?: DataSourceReference[];
}

/** Parameters for creating a database */
export interface CreateDatabaseParams {
  /** Parent page for the database */
  parent: { type: "page_id"; page_id: string };
  /** Database title */
  title?: Array<{ text: { content: string } }>;
  /** Database property schema definitions */
  properties: Record<string, unknown>;
}

/** Parameters for updating a database */
export interface UpdateDatabaseParams {
  /** Updated title */
  title?: Array<{ text: { content: string } }>;
  /** Updated description */
  description?: Array<{ text: { content: string } }>;
  /** Updated property schema definitions */
  properties?: Record<string, unknown>;
}

/** Parameters for querying a database */
export interface QueryDatabaseParams {
  /** Filter to apply to the query */
  filter?: unknown;
  /** Sorts to apply to the query */
  sorts?: unknown[];
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from query database endpoint */
export interface QueryDatabaseResponse {
  object: "list";
  results: NotionPage[];
  next_cursor: string | null;
  has_more: boolean;
}

// ============================================================================
// Data Sources API types
// ============================================================================

/** Parameters for querying a data source */
export interface QueryDataSourceParams {
  /** Filter to apply to the query */
  filter?: unknown;
  /** Sorts to apply to the query */
  sorts?: unknown[];
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/** Response from query data source endpoint */
export interface QueryDataSourceResponse {
  object: "list";
  results: NotionPage[];
  next_cursor: string | null;
  has_more: boolean;
}

/** Parameters for creating a data source */
export interface CreateDataSourceParams {
  /** Parent database */
  parent: { type: "database_id"; database_id: string };
  /** Data source title */
  title?: Array<{ text: { content: string } }>;
  /** Data source property schema definitions */
  properties: Record<string, unknown>;
}

/** Parameters for updating a data source */
export interface UpdateDataSourceParams {
  /** Updated title */
  title?: Array<{ text: { content: string } }>;
  /** Updated property schema definitions */
  properties?: Record<string, unknown>;
}

// ============================================================================
// Move Page types
// ============================================================================

/** Parameters for moving a page to a new parent */
export interface MovePageParams {
  /** New parent for the page */
  parent: { type: "page_id"; page_id: string } | { type: "database_id"; database_id: string };
}
