/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Variables for Notion API collection.
 */

export const variables = {
  collection: {
    BEARER_TOKEN: "",
    DATABASE_ID: "",
    USER_ID: "",
    PAGE_ID: "",
    BLOCK_ID: "",
    NOTION_VERSION: "2025-09-03",
    DISCUSSION_ID: "",
    PROPERTY_ID: "",
    COMMENT_ID: "",
    DATA_SOURCE_ID: "",
    FILE_UPLOAD_ID: "",
  },
};
