/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Variables for Notion API collection.
 */

export const variables = {
  collection: {
    BEARER_TOKEN: "",
    DATABASE_ID: "",
    USER_ID: "",
    PAGE_ID: "",
    BLOCK_ID: "",
    NOTION_VERSION: "2022-02-22",
    DISCUSSION_ID: "",
    PROPERTY_ID: "",
  },
};
