/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Retrieve a page
 * Request UID: 52041987-d7e520f6-0c75-4fe0-9b23-990f742d496e
 * Request modified at: 2023-09-04T19:08:43.000Z
 */

import type { NotionPage, NotionError } from "../../shared/types.js";

/**
 * Retrieve a page by ID.
 *
 * Retrieves a Page object using the ID in the request path.
 * This endpoint exposes page properties, not page content (use blocks API for content).
 *
 * @param pageId - The ID of the page to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The page object with properties
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-page
 */
export async function retrievePage(
  pageId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionPage> {
  const url = `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
