/**
 * Generated by Postman Code
 *
 * Collection: Notion API
 * Collection UID: 15568543-d990f9b7-98d3-47d3-9131-4866ab9c6df2
 *
 * Request: Pages > Retrieve a page
 * Request UID: 15568543-8a70cbd1-7dbe-4699-a04e-108084a9c31b
 * Request modified at: 2023-09-04T19:08:43.000Z
 */

import type { NotionPage, NotionError } from "../../shared/types.js";

/**
 * Retrieve a page by ID.
 *
 * Retrieves a Page object using the ID in the request path.
 * This endpoint exposes page properties, not page content (use blocks API for content).
 *
 * @param pageId - The ID of the page to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version (default: 2022-02-22)
 * @returns The page object with properties
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-page
 */
export async function retrievePage(
  pageId: string,
  bearerToken: string,
  notionVersion: string = "2022-02-22"
): Promise<NotionPage> {
  const url = `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
