/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Data sources > Create a data source
 * Request UID: 52041987-9c41977a-1606-4c76-a4e0-d094a3d0b4c7
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type {
  CreateDataSourceParams,
  NotionDatabase,
  NotionError,
} from "../../shared/types.js";

/**
 * Create a new data source in a database.
 *
 * Creates a new data source in the specified parent database.
 *
 * @param params - Data source creation parameters (parent, title, properties)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The created data source object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/create-a-data-source
 */
export async function createDataSource(
  params: CreateDataSourceParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const url = "https://api.notion.com/v1/data_sources";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
