/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Blocks > Update a block
 * Request UID: 52041987-1a96de40-de2c-49c8-9697-fc91b077d06d
 * Request modified at: 2022-03-02T05:38:38.000Z
 */

import type { NotionBlock, NotionError } from "../../shared/types.js";

/**
 * Update a block's content.
 *
 * The request body should include the block type key with the updated
 * fields. For example, to update a paragraph block:
 *   { paragraph: { rich_text: [{ text: { content: "new text" } }] } }
 *
 * Can also update the archived status to delete/restore a block.
 *
 * @param blockId - The ID of the block to update
 * @param params - Block content to update (varies by block type)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The updated block object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/update-a-block
 */
export async function updateBlock(
  blockId: string,
  params: Record<string, unknown>,
  bearerToken: string,
  notionVersion: string
): Promise<NotionBlock> {
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionBlock;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
