/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Blocks > Retrieve a block
 * Request UID: 52041987-30ea7fcd-b8b4-441f-935a-c9d143d59d66
 * Request modified at: 2022-02-24T23:01:58.000Z
 */

import type { NotionBlock, NotionError } from "../../shared/types.js";

/**
 * Retrieve a single block object by ID.
 *
 * @param blockId - The ID of the block to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The block object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-block
 */
export async function retrieveBlock(
  blockId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionBlock> {
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionBlock;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
