/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Data sources > Update a data source
 * Request UID: 52041987-29f06253-bd7e-4c3c-b0d8-a36b285c4e0e
 * Request modified at: 2026-02-02T22:36:03.000Z
 */

import type {
  UpdateDataSourceParams,
  NotionDatabase,
  NotionError,
} from "../../shared/types.js";

/**
 * Update a data source.
 *
 * Updates the specified data source object.
 *
 * @param dataSourceId - The ID of the data source to update
 * @param params - Properties to update (title, properties schema)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The updated data source object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/update-a-data-source
 */
export async function updateDataSource(
  dataSourceId: string,
  params: UpdateDataSourceParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const url = `https://api.notion.com/v1/data_sources/${encodeURIComponent(dataSourceId)}`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
