/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Comments > Retrieve a comment
 * Request UID: 52041987-2f312153-d16c-459b-9d51-88358a96fe03
 * Request modified at: 2026-02-02T22:36:03.000Z
 */

import type { NotionComment, NotionError } from "../../shared/types.js";

/**
 * Retrieve a single comment by ID.
 *
 * @param commentId - The ID of the comment to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The comment object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-comment
 */
export async function retrieveComment(
  commentId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionComment> {
  const url = `https://api.notion.com/v1/comments/${encodeURIComponent(commentId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionComment;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
