/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Blocks > Delete a block
 * Request UID: 52041987-95e3f732-e993-42b4-8451-70178b3d2ac9
 * Request modified at: 2022-02-24T23:00:56.000Z
 */

import type { NotionBlock, NotionError } from "../../shared/types.js";

/**
 * Delete (archive) a block.
 *
 * Sets a block's archived property to true. The block can be restored
 * via the update block endpoint by setting archived to false.
 *
 * @param blockId - The ID of the block to delete
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The deleted block object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/delete-a-block
 */
export async function deleteBlock(
  blockId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionBlock> {
  const url = `https://api.notion.com/v1/blocks/${encodeURIComponent(blockId)}`;

  const response = await fetch(url, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionBlock;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
