/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Databases > Update a database
 * Request UID: 52041987-5febd2f6-c9ff-486d-8a4b-71e5c58f82ef
 * Request modified at: 2023-09-04T19:04:51.000Z
 */

import type { UpdateDatabaseParams, NotionDatabase, NotionError } from "../../shared/types.js";

/**
 * Update a database's title, description, or properties.
 *
 * Only the fields included in the request body are updated;
 * omitted fields remain unchanged.
 *
 * @param databaseId - The ID of the database to update
 * @param params - Fields to update (title, description, properties)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The updated database object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/update-a-database
 */
export async function updateDatabase(
  databaseId: string,
  params: UpdateDatabaseParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const url = `https://api.notion.com/v1/databases/${encodeURIComponent(databaseId)}`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
