/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Update page properties
 * Request UID: 52041987-de2726f0-1465-4fdc-81d5-bd35415848b4
 * Note: Archive uses PATCH /v1/pages/{id} with { archived: true } — same as Update page properties
 * Request modified at: 2023-09-05T16:35:20.000Z
 */

import type { NotionPage, NotionError } from "../../shared/types.js";

/**
 * Archive (soft-delete) a page.
 *
 * Sets the page's archived property to true. The page can be restored
 * later by setting archived back to false via the update endpoint.
 *
 * @param pageId - The ID of the page to archive
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The archived page object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/archive-a-page
 */
export async function archivePage(
  pageId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionPage> {
  const url = `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}`;

  const response = await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify({ archived: true }),
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
