/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: File uploads > Create a file upload
 * Request UID: 52041987-1548ae35-ac12-4fc3-a337-416ed2a92088
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type { NotionError } from "../../shared/types.js";

/** Parameters for creating a file upload */
export interface CreateFileUploadParams {
  /** How the file is being sent. Default is "single_part". */
  mode?: "single_part" | "multi_part" | "external_url";
  /** Name of the file. Must include an extension, or have one inferred from content_type. */
  filename?: string;
  /** MIME type of the file. */
  content_type?: string;
  /** When mode is "multi_part", the number of parts being uploaded. */
  number_of_parts?: number;
  /** When mode is "external_url", the HTTPS URL of a publicly accessible file. */
  external_url?: string;
}

/** File upload object returned by the Notion API */
export interface FileUpload {
  object: "file_upload";
  id: string;
  created_time: string;
  created_by: { id: string; type: string };
  last_edited_time: string;
  archived: boolean;
  expiry_time: string | null;
  status: "pending" | "uploaded" | "expired" | "failed";
  filename: string | null;
  content_type: string | null;
  content_length: number | null;
  upload_url?: string;
  complete_url?: string;
  number_of_parts?: { total: number; sent: number };
}

/**
 * Initialize a new file upload.
 *
 * @param params - File upload parameters (mode, filename, content_type)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The created file upload object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/create-a-file-upload
 */
export async function createFileUpload(
  params: CreateFileUploadParams,
  bearerToken: string,
  notionVersion: string
): Promise<FileUpload> {
  const url = "https://api.notion.com/v1/file_uploads";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as FileUpload;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
