/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Users > List all users
 * Request UID: 52041987-1f6b9bec-dc7d-4412-9e80-46a33b8b11c6
 * Request modified at: 2022-03-02T05:38:37.000Z
 */

import type { ListUsersParams, ListUsersResponse, NotionError } from "../../shared/types.js";

/**
 * Returns a paginated list of user objects for the workspace.
 *
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional pagination parameters
 * @returns Paginated list of user objects
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/get-users
 */
export async function listUsers(
  bearerToken: string,
  notionVersion: string,
  params?: ListUsersParams
): Promise<ListUsersResponse> {
  const url = new URL("https://api.notion.com/v1/users");

  if (params?.start_cursor) {
    url.searchParams.set("start_cursor", params.start_cursor);
  }
  if (params?.page_size !== undefined) {
    url.searchParams.set("page_size", String(params.page_size));
  }

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as ListUsersResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
