/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Data sources > Retrieve a data source
 * Request UID: 52041987-dfeeac14-f85e-4527-ad2e-d85f79284dd9
 * Request modified at: 2026-02-02T22:36:03.000Z
 */

import type { NotionDatabase, NotionError } from "../../shared/types.js";

/**
 * Retrieve a data source by ID.
 *
 * Retrieves a data source object using the ID specified. To get data source IDs,
 * first call GET /v1/databases/{database_id} and extract IDs from the data_sources
 * array.
 *
 * @param dataSourceId - The ID of the data source to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The data source object with schema
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-data-source
 */
export async function retrieveDataSource(
  dataSourceId: string,
  bearerToken: string,
  notionVersion: string
): Promise<NotionDatabase> {
  const url = `https://api.notion.com/v1/data_sources/${encodeURIComponent(dataSourceId)}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as NotionDatabase;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
