/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Databases > Query a database
 * Request UID: 15568543-cddcc0aa-d534-4744-b37a-ddf36dee7d8f
 * Note: This endpoint is REMOVED in the 2025-09-03 API. Use query-data-source instead.
 * Kept for backwards compatibility during migration.
 * Request modified at: 2023-09-05T16:53:05.000Z
 */

import type {
  QueryDatabaseParams,
  QueryDatabaseResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Query a database.
 *
 * Gets a list of pages contained in the database, filtered and ordered
 * according to the filter and sort criteria provided in the request body.
 *
 * @param databaseId - The ID of the database to query
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional filter, sort, and pagination parameters
 * @returns Paginated list of pages in the database
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-database-query
 */
export async function queryDatabase(
  databaseId: string,
  bearerToken: string,
  notionVersion: string,
  params: QueryDatabaseParams = {}
): Promise<QueryDatabaseResponse> {
  const url = `https://api.notion.com/v1/databases/${encodeURIComponent(databaseId)}/query`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as QueryDatabaseResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
