/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: File uploads > List file uploads
 * Request UID: 52041987-d6b82f81-aaf2-4cc0-b92c-c8cdf709e67d
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type { NotionError } from "../../shared/types.js";
import type { FileUpload } from "../create-file-upload/client.js";

/** Response from list file uploads endpoint */
export interface ListFileUploadsResponse {
  object: "list";
  results: FileUpload[];
  next_cursor: string | null;
  has_more: boolean;
}

/** Parameters for listing file uploads */
export interface ListFileUploadsParams {
  /** Cursor for pagination */
  start_cursor?: string;
  /** Number of results per page (max 100) */
  page_size?: number;
}

/**
 * List file uploads.
 *
 * Returns a paginated list of file uploads.
 *
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional pagination parameters
 * @returns Paginated list of file uploads
 * @throws Error if the request fails
 */
export async function listFileUploads(
  bearerToken: string,
  notionVersion: string,
  params: ListFileUploadsParams = {}
): Promise<ListFileUploadsResponse> {
  const queryParams = new URLSearchParams();
  if (params.start_cursor) queryParams.set("start_cursor", params.start_cursor);
  if (params.page_size) queryParams.set("page_size", String(params.page_size));

  const qs = queryParams.toString();
  const url = `https://api.notion.com/v1/file_uploads${qs ? `?${qs}` : ""}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as ListFileUploadsResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
