/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Retrieve a page property item
 * Request UID: 52041987-e3c019ad-9c8b-4975-a142-5549ef771028
 * Request modified at: 2023-09-05T16:45:46.000Z
 */

import type { PagePropertyItemResponse, NotionError } from "../../shared/types.js";

/**
 * Retrieve a page property item by page ID and property ID.
 *
 * For most property types this returns the value directly. For paginated
 * properties (e.g. rollups, relations with many entries, rich_text, title)
 * the response includes pagination fields.
 *
 * @param pageId - The ID of the page
 * @param propertyId - The ID of the property to retrieve
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional pagination parameters
 * @returns The property item (or paginated list of property items)
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-page-property
 */
export async function retrievePageProperty(
  pageId: string,
  propertyId: string,
  bearerToken: string,
  notionVersion: string,
  params?: { start_cursor?: string; page_size?: number }
): Promise<PagePropertyItemResponse> {
  const url = new URL(
    `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}/properties/${encodeURIComponent(propertyId)}`
  );

  if (params?.start_cursor) {
    url.searchParams.set("start_cursor", params.start_cursor);
  }
  if (params?.page_size !== undefined) {
    url.searchParams.set("page_size", String(params.page_size));
  }

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as PagePropertyItemResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
