/**
 * Generated by Postman Code
 *
 * Collection: ⭐️ Stripe API [2024-04-10]
 * Collection UID: 665823-7a054d2e-29d8-441a-8752-fb9b93d71384
 *
 * Request: Payment Intents > Confirm a PaymentIntent
 * Request UID: 665823-994aec12-2eb2-4749-b981-5d0a4cbfcfc2
 * Request modified at: 2024-04-16T16:37:09.000Z
 */

import type { ConfirmPaymentIntentParams, PaymentIntent, StripeError } from '../../shared/types.js';

/**
 * Confirms that your customer intends to pay with current or provided payment method.
 *
 * Upon confirmation, the PaymentIntent will attempt to initiate a payment.
 * If the selected payment method requires additional authentication steps,
 * the PaymentIntent will transition to the `requires_action` status.
 * If payment succeeds, the PaymentIntent will transition to the `succeeded` status.
 *
 * @param apiKey - Stripe secret API key
 * @param baseUrl - Stripe API base URL
 * @param intentId - The PaymentIntent ID (starts with pi_)
 * @param params - Optional confirmation parameters
 * @returns The confirmed PaymentIntent
 * @throws Error if the request fails
 *
 * @example
 * const paymentIntent = await confirmPaymentIntent(
 *   'sk_test_...',
 *   'https://api.stripe.com',
 *   'pi_1234567890',
 *   { payment_method: 'pm_card_visa' }
 * );
 */
export async function confirmPaymentIntent(
  apiKey: string,
  baseUrl: string,
  intentId: string,
  params: ConfirmPaymentIntentParams = {}
): Promise<PaymentIntent> {
  const url = `${baseUrl}/v1/payment_intents/${intentId}/confirm`;

  // Build form-urlencoded body
  const body = new URLSearchParams();

  if (params.payment_method) {
    body.append('payment_method', params.payment_method);
  }

  if (params.return_url) {
    body.append('return_url', params.return_url);
  }

  // Handle inline payment method data
  if (params.payment_method_data) {
    body.append('payment_method_data[type]', params.payment_method_data.type);

    if (params.payment_method_data.type === 'card' && params.payment_method_data.card) {
      const card = params.payment_method_data.card;
      body.append('payment_method_data[card][number]', card.number);
      body.append('payment_method_data[card][exp_month]', String(card.exp_month));
      body.append('payment_method_data[card][exp_year]', String(card.exp_year));
      body.append('payment_method_data[card][cvc]', card.cvc);
    }
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: body.toString(),
  });

  const data = await response.json();

  if (!response.ok) {
    const error = data as StripeError;
    const message = error.error?.message || 'Unknown error';
    const code = error.error?.code || 'unknown';
    throw new Error(`Stripe API error (${code}): ${message}`);
  }

  return data as PaymentIntent;
}

