# Generated by Postman Code
#
# Shared error handling for SearchApi Google Maps collections.
# All five collections return the same error response shape:
#   {"error": "<message>"}
# with status codes 400, 401, 429, 500, 503.

import requests


class SearchApiError(Exception):
    """Base exception for SearchApi errors."""

    def __init__(self, status_code: int, message: str):
        self.status_code = status_code
        self.message = message
        super().__init__(f"[{status_code}] {message}")


class ValidationError(SearchApiError):
    """400 — Invalid or missing query parameters."""
    pass


class AuthenticationError(SearchApiError):
    """401 — API key is missing or invalid."""
    pass


class RateLimitError(SearchApiError):
    """429 — Request limit exceeded."""
    pass


class ServerError(SearchApiError):
    """500 — Internal server error."""
    pass


class TimeoutError(SearchApiError):
    """503 — Results could not be retrieved within 90 seconds."""
    pass


_STATUS_MAP: dict[int, type[SearchApiError]] = {
    400: ValidationError,
    401: AuthenticationError,
    429: RateLimitError,
    500: ServerError,
    503: TimeoutError,
}


def handle_response(response: requests.Response) -> dict:
    """Parse a SearchApi response, raising typed errors for known status codes.

    Returns the parsed JSON on success (2xx). For error responses, extracts
    the error message from the response body and raises the appropriate
    SearchApiError subclass.
    """
    if response.ok:
        return response.json()

    error_class = _STATUS_MAP.get(response.status_code, SearchApiError)
    try:
        body = response.json()
        message = body.get("error", response.text)
    except Exception:
        message = response.text

    raise error_class(response.status_code, message)
