# Generated by Postman Code
#
# Collection: Google Maps Search API
# Collection UID: 45090949-36a5cde4-8b66-450f-b3d5-d28cfb535b56

variables = {
    "collection": {
        "baseUrl": "https://www.searchapi.io/api/v1",
    },
    "Production": {
        "baseUrl": "",
    },
}
