# Generated by Postman Code
#
# Collection: Google Maps Place API
# Collection UID: 45090949-0fe19c7c-d780-47f7-9aa9-b9657be38fa9
#
# Request: search > Google Maps Place Details
# Request UID: 45090949-042e4345-e1ab-4e8b-b45d-c027e3cd0b2a
# Request modified at: 2025-09-07T03:23:37.000Z

from typing import TypedDict

import requests

from postman.google_maps_search_api.shared.errors import (
    SearchApiError,
    handle_response,
)


class GpsCoordinates(TypedDict, total=False):
    latitude: float
    longitude: float


class Temperature(TypedDict, total=False):
    fahrenheit: int
    celsius: int


class Weather(TypedDict, total=False):
    temperature: Temperature
    conditions: str


class ReviewsHistogram(TypedDict, total=False):
    """Star rating distribution, keys are "1" through "5"."""
    pass


class PricingOffer(TypedDict, total=False):
    source: str
    price: str
    extracted_price: float
    price_with_taxes: str
    extracted_price_with_taxes: float
    tracking_link: str
    highlights: list[str]


class PricingOffers(TypedDict, total=False):
    featured_options: list[PricingOffer]
    all_options: list[PricingOffer]


class Pricing(TypedDict, total=False):
    start_date: str
    end_date: str
    offers: PricingOffers


class Reservation(TypedDict, total=False):
    link: str
    source: str


class Image(TypedDict, total=False):
    title: str
    thumbnail: str


class ExtensionItem(TypedDict, total=False):
    title: str
    value: str


class Extension(TypedDict, total=False):
    title: str
    items: list[ExtensionItem]


class Post(TypedDict, total=False):
    title: str
    source: str
    link: str


class ReservationLink(TypedDict, total=False):
    text: str
    link: str


class Review(TypedDict, total=False):
    username: str
    rating: float
    contributor_id: str
    description: str
    link: str
    date: str
    images: list[str]


class WebReviewResult(TypedDict, total=False):
    username: str
    link: str
    rating: int
    description: str
    date: str


class WebReview(TypedDict, total=False):
    name: str
    rating: float
    reviews: int
    review_results: list[WebReviewResult]


class HotelSummaryAspect(TypedDict, total=False):
    rating: float
    text: str


class HotelSummary(TypedDict, total=False):
    rooms: HotelSummaryAspect
    location: HotelSummaryAspect
    service_and_facilities: HotelSummaryAspect


class ReviewResults(TypedDict, total=False):
    hotel_summary: HotelSummary
    summaries: list[str]
    reviews: list[Review]
    web_reviews: list[WebReview]


class BusynessEntry(TypedDict, total=False):
    time: str
    busyness_score: int
    info: str


class PopularTimesLive(TypedDict, total=False):
    info: str
    typical_time_spent: str


class PopularTimes(TypedDict, total=False):
    live: PopularTimesLive
    chart: dict[str, list[BusynessEntry]]


class PlaceResult(TypedDict, total=False):
    ludocid: str
    place_id: str
    kgmid: str
    data_id: str
    title: str
    description: str
    weather: Weather
    features: str
    address: str
    located_in: str
    is_entity_closed: bool
    operational_status: str
    phone: str
    plus_code: str
    price: str
    price_description: str
    hotel_stars: str
    rating: float
    reviews: int
    reviews_histogram: dict[str, int]
    reviews_link: str
    pricing: Pricing
    is_unclaimed_listing: bool
    website: str
    domain: str
    gps_coordinates: GpsCoordinates
    type: str
    types: list[str]
    reservation: Reservation
    menu: Reservation
    amenities: list[str]
    open_state: str
    hours: str
    open_hours: dict[str, str]
    reservation_links: list[ReservationLink]
    booking_link: str
    thumbnail: str
    images: list[Image]
    extensions: list[Extension]
    posts: list[Post]
    questions_and_answers: dict
    review_results: ReviewResults
    popular_times: PopularTimes


class GoogleMapsPlaceDetailsResponse(TypedDict, total=False):
    search_metadata: dict
    search_parameters: dict
    place_result: PlaceResult
    error: str


def google_maps_place_details(
    base_url: str,
    api_key: str,
    place_id: str | None = None,
    data_id: str | None = None,
    google_domain: str = "google.com",
    hl: str = "en",
) -> GoogleMapsPlaceDetailsResponse:
    """Get detailed information about a specific place on Google Maps.

    Provide either place_id or data_id (at least one is required). These
    identifiers come from Google Maps Search results.

    Args:
        base_url: The API base URL (e.g. "https://www.searchapi.io/api/v1").
        api_key: SearchApi API key for authentication.
        place_id: Google Maps place ID (from search results).
        data_id: Google Maps data ID (from search results).
        google_domain: Google domain to use (default "google.com").
        hl: Language for search results (default "en").

    Returns:
        GoogleMapsPlaceDetailsResponse with:
            - place_result: comprehensive place data including title, address,
              phone, rating, reviews, reviews_histogram, website,
              gps_coordinates, type, open_state, hours, amenities,
              popular_times, review_results, images, pricing.

    Raises:
        ValidationError: 400 — invalid or missing query parameters.
        AuthenticationError: 401 — API key is missing or invalid.
        RateLimitError: 429 — request limit exceeded.
        ServerError: 500 — internal server error.
        TimeoutError: 503 — results not retrieved within 90 seconds.
    """
    params: dict = {
        "engine": "google_maps_place",
        "api_key": api_key,
        "google_domain": google_domain,
        "hl": hl,
    }
    if place_id is not None:
        params["place_id"] = place_id
    if data_id is not None:
        params["data_id"] = data_id

    response = requests.get(
        f"{base_url}/search",
        params=params,
        headers={"Accept": "application/json"},
    )
    return handle_response(response)
