/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Create a page
 * Request UID: 52041987-a2ef9963-62e0-4e87-a12b-f899f695280c
 * Request modified at: 2023-09-04T19:05:19.000Z
 */

import type { CreatePageParams, NotionPage, NotionError } from "../../shared/types.js";

/**
 * Create a new page in Notion.
 *
 * The page can be created under a parent page or inside a database.
 * When created in a database, properties must match the database schema.
 *
 * @param params - Page creation parameters (parent, properties, optional children)
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The created page object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-page
 */
export async function createPage(
  params: CreatePageParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionPage> {
  const response = await fetch("https://api.notion.com/v1/pages/", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
