/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Comments > Retrieve comments
 * Request UID: 52041987-4def4425-319e-418c-9d96-56a4807a8ce7
 * Request modified at: 2022-07-20T17:24:31.000Z
 */

import type { RetrieveCommentsParams, RetrieveCommentsResponse, NotionError } from "../../shared/types.js";

/**
 * Retrieve comments for a block or page.
 *
 * Returns a paginated list of comment objects for the given block_id.
 * Pages are also blocks, so a page ID can be used here.
 *
 * @param blockId - The ID of the block or page to get comments for
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional pagination parameters
 * @returns Paginated list of comments
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/retrieve-a-comment
 */
export async function retrieveComments(
  blockId: string,
  bearerToken: string,
  notionVersion: string,
  params?: RetrieveCommentsParams
): Promise<RetrieveCommentsResponse> {
  const url = new URL("https://api.notion.com/v1/comments");
  url.searchParams.set("block_id", blockId);

  if (params?.start_cursor) {
    url.searchParams.set("start_cursor", params.start_cursor);
  }
  if (params?.page_size !== undefined) {
    url.searchParams.set("page_size", String(params.page_size));
  } else {
    url.searchParams.set("page_size", "100");
  }

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Notion-Version": notionVersion,
    },
  });

  if (response.ok) {
    return (await response.json()) as RetrieveCommentsResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
