/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Pages > Move page
 * Request UID: 52041987-9686de7b-77c0-4d53-b800-bf6c748bc668
 * Request modified at: 2026-02-02T22:36:37.000Z
 */

import type {
  MovePageParams,
  NotionPage,
  NotionError,
} from "../../shared/types.js";

/**
 * Move a page to a new parent page or database.
 *
 * @param pageId - The ID of the page to move
 * @param params - The new parent specification
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @returns The updated page object
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/move-a-page
 */
export async function movePage(
  pageId: string,
  params: MovePageParams,
  bearerToken: string,
  notionVersion: string
): Promise<NotionPage> {
  const url = `https://api.notion.com/v1/pages/${encodeURIComponent(pageId)}/move`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as NotionPage;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
