/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: OAuth > Revoke
 * Request UID: 52041987-2e4a8940-5ef0-42b2-9c3c-d56c1752e9ac
 * Request modified at: 2026-02-02T22:34:48.000Z
 */

import type { NotionError } from "../../shared/types.js";

/**
 * Revoke an access token or refresh token.
 *
 * This endpoint uses Basic authentication with your OAuth client_id and client_secret.
 *
 * @param token - The token to revoke
 * @param clientId - OAuth client ID
 * @param clientSecret - OAuth client secret
 * @throws Error if the request fails
 */
export async function oauthRevoke(
  token: string,
  clientId: string,
  clientSecret: string
): Promise<void> {
  const url = "https://api.notion.com/v1/oauth/revoke";
  const credentials = btoa(`${clientId}:${clientSecret}`);

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ token }),
  });

  if (!response.ok) {
    const error = (await response.json()) as NotionError;
    throw new Error(`Notion API error (${response.status}): ${error.message}`);
  }
}
