# Generated by Postman Code
#
# Collection: Google Maps Photos API
# Collection UID: 45090949-d1f6b805-2641-4ef3-bad7-6877b3f16348
#
# Request: search > Google Maps Photos Search
# Request UID: 45090949-0443dc38-81ae-4596-b0b5-f27b6139611c
# Request modified at: 2025-09-07T03:23:37.000Z

from typing import TypedDict

import requests

from postman.google_maps_search_api.shared.errors import (
    SearchApiError,
    handle_response,
)


class Category(TypedDict, total=False):
    id: str
    title: str


class Photo(TypedDict, total=False):
    image: str
    thumbnail: str


class Pagination(TypedDict, total=False):
    next_page_token: str


class GoogleMapsPhotosResponse(TypedDict, total=False):
    search_metadata: dict
    search_parameters: dict
    categories: list[Category]
    photos: list[Photo]
    pagination: Pagination


def google_maps_photos_search(
    base_url: str,
    api_key: str,
    place_id: str | None = None,
    data_id: str | None = None,
    hl: str = "en",
    category_id: str | None = None,
    next_page_token: str | None = None,
) -> GoogleMapsPhotosResponse:
    """Get photos associated with a place on Google Maps.

    Provide either place_id or data_id (at least one is required). These
    identifiers come from Google Maps Search or Place Details results.

    Args:
        base_url: The API base URL (e.g. "https://www.searchapi.io/api/v1").
        api_key: SearchApi API key for authentication.
        place_id: Google Maps place ID.
        data_id: Google Maps data ID.
        hl: Interface language (default "en").
        category_id: Filter photos by category (from the categories response field).
        next_page_token: Pagination token from a previous response.

    Returns:
        GoogleMapsPhotosResponse with:
            - categories: available photo categories with id and title.
            - photos: list of photos with full-size image and thumbnail URLs.
            - pagination: next_page_token for fetching more photos.

    Raises:
        ValidationError: 400 — invalid or missing query parameters.
        AuthenticationError: 401 — API key is missing or invalid.
        RateLimitError: 429 — request limit exceeded.
        ServerError: 500 — internal server error.
        TimeoutError: 503 — results not retrieved within 90 seconds.
    """
    params: dict = {
        "engine": "google_maps_photos",
        "api_key": api_key,
        "hl": hl,
    }
    if place_id is not None:
        params["place_id"] = place_id
    if data_id is not None:
        params["data_id"] = data_id
    if category_id is not None:
        params["category_id"] = category_id
    if next_page_token is not None:
        params["next_page_token"] = next_page_token

    response = requests.get(
        f"{base_url}/search",
        params=params,
        headers={"Accept": "application/json"},
    )
    return handle_response(response)
