/**
 * Generated by Postman Code
 *
 * Collection: ⭐️ Stripe API [2024-04-10]
 * Collection UID: 665823-7a054d2e-29d8-441a-8752-fb9b93d71384
 *
 * Shared type definitions for Stripe API clients.
 *
 * ⚠️ WARNING: Response types (PaymentIntent, StripeError) were NOT sourced from
 * response examples in the Postman collection—the collection does not include them.
 * These types are inferred from general Stripe API knowledge and may be incomplete
 * or incorrect. In production, verify against Stripe's official API documentation:
 * https://stripe.com/docs/api/payment_intents/object
 */

export interface CardDetails {
  number: string;
  exp_month: number;
  exp_year: number;
  cvc: string;
}

export interface CardPaymentMethodData {
  type: "card";
  card: CardDetails;
}

export interface BillingDetails {
  name?: string;
  email?: string;
  phone?: string;
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
  };
}

export interface CreatePaymentIntentParams {
  /** Amount in smallest currency unit (e.g., cents) */
  amount: number;
  /** Three-letter ISO currency code (e.g., 'usd') */
  currency: string;
  /** Whether to confirm the PaymentIntent immediately */
  confirm?: boolean;
  /** Inline payment method data */
  payment_method_data?: CardPaymentMethodData;
  /** ID of an existing PaymentMethod */
  payment_method?: string;
  /** Description of the payment */
  description?: string;
  /** Email to send receipt to */
  receipt_email?: string;
  /** URL to redirect after authentication */
  return_url?: string;
  /** Automatic payment methods configuration */
  automatic_payment_methods?: {
    enabled: boolean;
    allow_redirects?: "always" | "never";
  };
}

export interface ConfirmPaymentIntentParams {
  /** ID of PaymentMethod to attach */
  payment_method?: string;
  /** Inline payment method data */
  payment_method_data?: CardPaymentMethodData;
  /** URL to redirect after authentication */
  return_url?: string;
}

export type PaymentIntentStatus =
  | "requires_payment_method"
  | "requires_confirmation"
  | "requires_action"
  | "processing"
  | "requires_capture"
  | "canceled"
  | "succeeded";

/**
 * ⚠️ UNVERIFIED TYPE - Not sourced from Postman response examples.
 * The actual Stripe PaymentIntent object has many more fields.
 * See: https://stripe.com/docs/api/payment_intents/object
 */
export interface PaymentIntent {
  /** Unique identifier (starts with pi_) */
  id: string;
  /** Object type */
  object: "payment_intent";
  /** Amount in smallest currency unit */
  amount: number;
  /** Amount that was collected */
  amount_received: number;
  /** Three-letter ISO currency code */
  currency: string;
  /** Payment status */
  status: PaymentIntentStatus;
  /** Secret for client-side confirmation */
  client_secret: string | null;
  /** Description of the payment */
  description: string | null;
  /** ID of the PaymentMethod used */
  payment_method: string | null;
  /** Unix timestamp of creation */
  created: number;
  /** Whether this is a live payment */
  livemode: boolean;
  /** Details of the last payment error, if any */
  last_payment_error?: {
    type: string;
    message: string;
    code?: string;
  };
}

/**
 * ⚠️ UNVERIFIED TYPE - Not sourced from Postman response examples.
 * See: https://stripe.com/docs/api/errors
 */
export interface StripeError {
  error: {
    type: string;
    message: string;
    code?: string;
    param?: string;
  };
}
