/**
 * Generated by Postman Code
 *
 * Collection: ⭐️ Stripe API [2024-04-10]
 * Collection UID: 665823-7a054d2e-29d8-441a-8752-fb9b93d71384
 *
 * Variables extracted from the Stripe API collection.
 */

export const variables = {
  collection: {
    baseUrl: "https://api.stripe.com",
  },
  test: {
    // Caller should provide Stripe test secret key (starts with sk_test_)
    apiKey: "",
  },
  live: {
    // Caller should provide Stripe live secret key (starts with sk_live_)
    apiKey: "",
  },
} as const;
