/**
 * Generated by Postman Code
 *
 * Collection: Notion API (2025-09-03)
 * Collection UID: 52041987-03f70d8f-b6e5-4306-805c-f95f7cdf05b9
 *
 * Request: Data sources > Query a data source
 * Request UID: 52041987-aa498c21-f7e7-4839-bbe7-78957fb7379d
 * Request modified at: 2026-02-02T22:36:03.000Z
 */

import type {
  QueryDataSourceParams,
  QueryDataSourceResponse,
  NotionError,
} from "../../shared/types.js";

/**
 * Query a data source.
 *
 * Queries a data source and returns matching results. This replaces the old
 * POST /v1/databases/{database_id}/query endpoint.
 *
 * IMPORTANT: You must use a data_source_id, NOT a database_id. To get the
 * data_source_id, first call GET /v1/databases/{database_id} and extract the
 * ID from the data_sources array in the response.
 *
 * @param dataSourceId - The ID of the data source to query
 * @param bearerToken - Notion API bearer token (integration secret)
 * @param notionVersion - Notion API version
 * @param params - Optional filter, sort, and pagination parameters
 * @returns Paginated list of pages in the data source
 * @throws Error if the request fails
 *
 * @see https://developers.notion.com/reference/post-data-source-query
 */
export async function queryDataSource(
  dataSourceId: string,
  bearerToken: string,
  notionVersion: string,
  params: QueryDataSourceParams = {}
): Promise<QueryDataSourceResponse> {
  const url = `https://api.notion.com/v1/data_sources/${encodeURIComponent(dataSourceId)}/query`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${bearerToken}`,
      "Content-Type": "application/json",
      "Notion-Version": notionVersion,
    },
    body: JSON.stringify(params),
  });

  if (response.ok) {
    return (await response.json()) as QueryDataSourceResponse;
  }

  const error = (await response.json()) as NotionError;
  throw new Error(`Notion API error (${response.status}): ${error.message}`);
}
